// ============================================================================
//  trail/hashChain — the op-stream chain hash, v2, as the specification pins it.
//
//  Each recorded op carries the hash of the op before it, so re-ordering the
//  trail, dropping an op out of the middle, or RE-ATTRIBUTING one — quietly
//  relabelling a human edit as a model emission, or the reverse — moves every
//  hash from that point on. The actor is inside the pre-image; that is what
//  makes attribution evidence rather than assertion.
//
//  ── The pre-image, exactly ─────────────────────────────────────────────────
//
//    entry   = {"v":2,"op":<canonical op>,"ts":<unix seconds>,
//               "promptId":<string|null>,"result":<result>}
//    payload = {"seq":<sequence-1>,"actor":<actor>,"op":<entry>}
//    hash    = sha256Hex(previousHash + "|" + payload)
//
//  Three details that are easy to get subtly wrong and impossible to notice:
//
//   * `v` is the chain FORMAT version and is folded FIRST, so the pre-image is
//     self-describing. It is not the document version.
//   * `seq` in the payload is ZERO-BASED while the public argument is
//     one-based. The substrate records a 0-based index; the domain counts from
//     one. Both spellings are real, and the fold happens here.
//   * The separator `|` is INSIDE the hashed bytes, between the previous hash
//     and the payload. It is not a formatting nicety.
//
//  ── Why this is verified rather than believed ──────────────────────────────
//
//  The shared specification corpus ships `chain/chain-corpus.json`: golden
//  records generated by the canonical F# implementation, each naming a public
//  op fixture, an actor, a timestamp and the expected hash. Both the F# and
//  TypeScript reference hosts assert their chains reproduce those bytes, and
//  `test/hashChain.test.ts` makes this extension a third. That corpus is a
//  build input already (the relay fixtures and the wire schema come from the
//  same checkout), so the strongest available proof costs no new dependency.
//
//  ── The registry dependency that was considered and declined ───────────────
//
//  `@fuaran-ui/op-stream` is published (0.2.0 at the time of writing) and ships
//  a compatible `computeHash`. It was checked, and not adopted: its
//  `computeHash` takes a TYPED `TreeOp` and calls the `@fuaran-ui/ops` encoder,
//  so consuming it means taking `ops` + `schema` as well and decoding the
//  panel's structured ops into that package's types purely to re-encode them —
//  pinning the op vocabulary to one tier's release cadence, which is the
//  coupling this extension is deliberately without. What remains is a
//  pre-image formula of four lines and a SHA-256, and the browser supplies the
//  SHA-256. Dependency-free was cheaper AND better here, which is not always
//  true and is why it was checked rather than assumed.
//
//  ── SHA-256 comes from the platform ────────────────────────────────────────
//
//  `crypto.subtle.digest` rather than a vendored implementation: this code only
//  ever runs in a browser (an extension page is a secure context), and the
//  browser's own audited primitive beats seventy lines of ours. It is async,
//  which is why every function below returns a promise.
// ============================================================================

import { canonicalJson, encodeString, type JsonValue } from './canonicalJson.js';

/** The chain FORMAT version folded into every pre-image. */
export const CHAIN_FORMAT_VERSION = 2;

/** The `previousHash` of a chain with nothing before it — sixty-four zeroes. */
export const GENESIS_PREVIOUS_HASH = '0'.repeat(64);

/**
 * The fixed instant the session-log family stamps into every pre-image.
 *
 * 2020-01-01T00:00:00Z. The document does NOT carry it, so a verifier has to
 * know it — which makes it part of the export contract rather than an
 * implementation detail. A recording that stamped wall-clock time would be
 * unverifiable by anyone who did not also receive the clock, and would leak
 * edit timing into a hash for no benefit.
 */
export const CHAIN_TIMESTAMP_UNIX_SECONDS = 1_577_836_800;

/** Who made a change. The `Actor` of the op-stream, in its wire spelling. */
export type Actor =
  | { readonly kind: 'human'; readonly id: string }
  | {
      readonly kind: 'agent';
      readonly model: string;
      readonly version: string;
      readonly id: string;
    };

/** The outcome recorded against an op. The trail records applied ops only. */
export type OpResult =
  | { readonly kind: 'success' }
  | { readonly kind: 'failure'; readonly code: string; readonly message: string };

export const SUCCESS: OpResult = { kind: 'success' };

/**
 * The actor every op this extension applies is attributed to.
 *
 * Distinct from the relay's `attribution.actor` string (`"fuaran-devtools"`),
 * which is free-form advisory metadata for the HOST's audit trail and grants
 * nothing (DEVTOOLS_RELAY §8.2). This one is the op-stream `Actor` folded into
 * the chain hash, and it is the identity the exported trail attests to.
 */
export const DEVTOOLS_ACTOR: Actor = { kind: 'human', id: 'devtools' };

/**
 * The actor's wire encoding — INSERTION-ordered, not ordinal-sorted.
 *
 * `kind` comes first and the rest follow in declaration order. This is the one
 * place in the document where keys are not sorted, and writing it through the
 * canonical encoder instead produces `{"id":…,"kind":…}` — a document that
 * looks right, verifies against nothing, and diverges from the reference
 * exporter by exactly two fields. Found by byte-comparison against a reference
 * document, which is the only way it would ever have been found.
 */
export const encodeActor = (actor: Actor): string =>
  actor.kind === 'human'
    ? `{"kind":"human","id":${encodeString(actor.id)}}`
    : `{"kind":"agent","model":${encodeString(actor.model)},"version":${encodeString(
        actor.version,
      )},"id":${encodeString(actor.id)}}`;

/**
 * Whether an actor id is safe to fold into a chain hash.
 *
 * The substrate encoder used INSIDE the pre-image spells a tab, newline or
 * carriage return with the two-character short escapes; the encoder used for
 * the EXPORTED actor field spells those same three as six-character lower-hex
 * unicode escapes. For every other character the two agree, so an id carrying
 * a control character would hash under one spelling and be published under the
 * other — a document that fails verification for a reason nothing in it
 * explains. Nothing here mints such an id (the actor is a module constant), and
 * this guard exists so that stays true if one ever comes from elsewhere.
 */
export const isEncodableActorId = (id: string): boolean => {
  for (const ch of id) if (ch < ' ') return false;
  return true;
};

export const encodeResult = (result: OpResult): string =>
  result.kind === 'success'
    ? '{"kind":"success"}'
    : `{"kind":"failure","code":${encodeString(result.code)},"message":${encodeString(
        result.message,
      )}}`;

/** The `{"v":2,…}` envelope the payload wraps. `opJson` is already canonical. */
export const encodeStreamEntry = (
  opJson: string,
  timestampUnixSeconds: number,
  promptId: string | undefined,
  result: OpResult,
): string =>
  `{"v":${CHAIN_FORMAT_VERSION},"op":${opJson},"ts":${Math.trunc(
    timestampUnixSeconds,
  )},"promptId":${promptId === undefined ? 'null' : encodeString(promptId)},"result":${encodeResult(
    result,
  )}}`;

/** SHA-256 of the UTF-8 bytes, as sixty-four lower-case hex characters. */
export const sha256Hex = async (payload: string): Promise<string> => {
  const digest = await crypto.subtle.digest('SHA-256', new TextEncoder().encode(payload));
  return Array.from(new Uint8Array(digest), (byte) => byte.toString(16).padStart(2, '0')).join('');
};

/** The chain hash of one op. `sequence` is the domain's ONE-based value. */
export const computeHash = async (
  previousHash: string,
  opJson: string,
  sequence: number,
  timestampUnixSeconds: number,
  actor: Actor,
  promptId: string | undefined,
  result: OpResult,
): Promise<string> => {
  const entry = encodeStreamEntry(opJson, timestampUnixSeconds, promptId, result);
  const payload = `{"seq":${sequence - 1},"actor":${encodeActor(actor)},"op":${entry}}`;
  return sha256Hex(`${previousHash}|${payload}`);
};

/**
 * The chain hash of an op held as a JSON value rather than canonical bytes —
 * the shape the panel actually has, canonicalised on the way in.
 */
export const computeHashOf = async (
  previousHash: string,
  op: JsonValue,
  sequence: number,
  actor: Actor,
): Promise<string> =>
  computeHash(
    previousHash,
    canonicalJson(op),
    sequence,
    CHAIN_TIMESTAMP_UNIX_SECONDS,
    actor,
    undefined,
    SUCCESS,
  );
