// ============================================================================
//  The chain hash, against the cross-host golden corpus.
//
//  `chain/chain-corpus.json` in the shared specification is the gate the F# and
//  TypeScript reference hosts already assert against: records generated by the
//  canonical implementation, each naming a public op fixture, an actor, a
//  timestamp, a prompt id and a result, with the hash those inputs must
//  produce. Reproducing them makes this extension a third implementation of the
//  same pre-image rather than a plausible-looking one.
//
//  This is the only kind of evidence worth having here. A chain hash that is
//  subtly wrong still produces a document full of sixty-four hex characters
//  that chain to each other perfectly; nothing about it looks wrong until
//  someone else tries to verify it, by which time the recordings are made.
//
//  Note the corpus exercises what a session log alone would not: an AGENT actor
//  (four fields, insertion-ordered), a non-null `promptId`, and a sequence past
//  the first. Those are the legs where a pre-image gets mis-assembled.
// ============================================================================

import { describe, expect, it } from 'vitest';

import { canonicalJson, type JsonValue } from '../src/trail/canonicalJson.js';
import {
  CHAIN_FORMAT_VERSION,
  computeHash,
  encodeActor,
  encodeResult,
  encodeStreamEntry,
  GENESIS_PREVIOUS_HASH,
  isEncodableActorId,
  sha256Hex,
  type Actor,
  type OpResult,
} from '../src/trail/hashChain.js';
import { readChainCorpus, readSpecText } from './support/corpus.js';

const corpus = readChainCorpus();

const asResult = (record: {
  readonly kind: string;
  readonly code?: string;
  readonly message?: string;
}): OpResult =>
  record.kind === 'success'
    ? { kind: 'success' }
    : { kind: 'failure', code: record.code ?? '', message: record.message ?? '' };

describe('the cross-host chain corpus', () => {
  it('declares the chain format version this implementation writes', () => {
    expect(corpus.version).toBe(CHAIN_FORMAT_VERSION);
  });

  it('agrees on the genesis hash', () => {
    expect(corpus.genesisPreviousHash).toBe(GENESIS_PREVIOUS_HASH);
  });

  it('is not empty', () => {
    expect(corpus.records.length).toBeGreaterThan(0);
  });

  for (const record of corpus.records)
    it(`reproduces the hash for ${record.opFixture} at sequence ${record.sequence}`, async () => {
      const op = JSON.parse(readSpecText(record.opFixture)) as JsonValue;
      const hash = await computeHash(
        record.previousHash,
        canonicalJson(op),
        record.sequence,
        record.timestampUnixSeconds,
        record.actor,
        record.promptId ?? undefined,
        asResult(record.result),
      );
      expect(hash).toBe(record.hash);
    });

  it('links each record to the one before it', async () => {
    let previous = corpus.genesisPreviousHash;
    for (const record of corpus.records) {
      expect(record.previousHash).toBe(previous);
      const op = JSON.parse(readSpecText(record.opFixture)) as JsonValue;
      previous = await computeHash(
        previous,
        canonicalJson(op),
        record.sequence,
        record.timestampUnixSeconds,
        record.actor,
        record.promptId ?? undefined,
        asResult(record.result),
      );
    }
  });
});

describe('the pre-image is assembled the way the specification pins it', () => {
  it('folds the chain format version first, and the timestamp as whole seconds', () => {
    expect(
      encodeStreamEntry('{"$type":"RemoveNode","target":"a"}', 1_700_000_000, undefined, {
        kind: 'success',
      }),
    ).toBe(
      '{"v":2,"op":{"$type":"RemoveNode","target":"a"},"ts":1700000000,' +
        '"promptId":null,"result":{"kind":"success"}}',
    );
  });

  it('encodes the actor in INSERTION order, not ordinal order', () => {
    // `{"id":…,"kind":…}` would be the canonical spelling and is wrong here.
    // The mistake is invisible in isolation and moves every hash in the file.
    expect(encodeActor({ kind: 'human', id: 'devtools' })).toBe('{"kind":"human","id":"devtools"}');
    const agent: Actor = { kind: 'agent', model: 'm', version: 'v', id: 'i' };
    expect(encodeActor(agent)).toBe('{"kind":"agent","model":"m","version":"v","id":"i"}');
  });

  it('encodes both result cases', () => {
    expect(encodeResult({ kind: 'success' })).toBe('{"kind":"success"}');
    expect(encodeResult({ kind: 'failure', code: 'C', message: 'm' })).toBe(
      '{"kind":"failure","code":"C","message":"m"}',
    );
  });

  it('changes the hash when only the ACTOR changes — attribution is evidence', async () => {
    const op = '{"$type":"RemoveNode","target":"a"}';
    const asHuman = await computeHash(
      GENESIS_PREVIOUS_HASH,
      op,
      1,
      0,
      { kind: 'human', id: 'x' },
      undefined,
      {
        kind: 'success',
      },
    );
    const asAgent = await computeHash(
      GENESIS_PREVIOUS_HASH,
      op,
      1,
      0,
      { kind: 'agent', model: 'm', version: '', id: 'x' },
      undefined,
      { kind: 'success' },
    );
    expect(asHuman).not.toBe(asAgent);
  });

  it('changes the hash when only the SEQUENCE changes', async () => {
    const op = '{"$type":"RemoveNode","target":"a"}';
    const actor: Actor = { kind: 'human', id: 'x' };
    const first = await computeHash(GENESIS_PREVIOUS_HASH, op, 1, 0, actor, undefined, {
      kind: 'success',
    });
    const second = await computeHash(GENESIS_PREVIOUS_HASH, op, 2, 0, actor, undefined, {
      kind: 'success',
    });
    expect(first).not.toBe(second);
  });
});

describe('sha256Hex', () => {
  it('produces sixty-four lower-case hex characters', async () => {
    expect(await sha256Hex('abc')).toBe(
      'ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad',
    );
  });

  it('hashes the UTF-8 bytes, so non-ASCII is not mangled', async () => {
    // Two bytes (C3 BC), not one. A latin-1 encoding would hash differently and
    // every document carrying a non-ASCII string would fail verification.
    expect(await sha256Hex('ü')).toBe(
      '607474ca475a9724d7360aba71a56d5df77e61350e3f724cfa1f46e857e2d85f',
    );
  });

  it('hashes the empty string', async () => {
    expect(await sha256Hex('')).toBe(
      'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
    );
  });
});

describe('actor ids that cannot be encoded consistently are recognised', () => {
  it('accepts the ids this extension uses', () => {
    expect(isEncodableActorId('devtools')).toBe(true);
  });

  it('rejects a control character, which the two encoders spell differently', () => {
    expect(isEncodableActorId('dev\ttools')).toBe(false);
    expect(isEncodableActorId('dev\ntools')).toBe(false);
  });
});
