// ============================================================================
//  The recording, end to end: panel → client → peer → host → back.
//
//  The unit suites pin each piece; this one drives the phase's acceptance
//  criteria against a host holding a real mutable tree, on the same wiring the
//  write-side suite uses:
//
//   * an undone edit leaves the host's tree BYTE-IDENTICAL to what it was —
//     asserted on the host's own full tree, property values and all, which is
//     the strongest available reading of "byte-identically" given the relay
//     returns no canonical tree;
//   * a refused op never appears in the trail;
//   * the exported document's chain verifies against an independent
//     recomputation, exactly as an ingest would verify it.
//
//  Be precise about what that last one proves. The verifier below re-derives
//  the chain the way an ingest does — walking the PARSED document, recomputing
//  each op's canonical bytes from its JSON, checking the sequence and the
//  links — but it calls the same `computeHash` the writer does. So it catches
//  the assembly going wrong (a seq off by one, a link to the undone op, an op's
//  bytes not matching what was hashed) and it does NOT catch the pre-image
//  formula going wrong, because both sides would move together.
//
//  That second job belongs to `test/hashChain.test.ts`, which asserts the
//  formula against the cross-host golden corpus generated by the canonical
//  implementation. Two suites, two different failures; neither substitutes for
//  the other, and saying "independently verified" here without that split
//  would be claiming coverage this file does not have.
// ============================================================================

import { describe, expect, it } from 'vitest';

import { RelayClient, type RelayTransport } from '../src/relay/client.js';
import { createPagePeer } from '../src/relay/pagePeer.js';
import type { RelayEnvelope, TreeSnapshot } from '../src/relay/protocol.js';
import { insertOp, removeNode, updateProp, type TreeOpJson } from '../src/edit/ops.js';
import { Trail } from '../src/trail/recorder.js';
import { computeHash, GENESIS_PREVIOUS_HASH, type Actor } from '../src/trail/hashChain.js';
import { canonicalJson } from '../src/trail/canonicalJson.js';
import { liveHost, node, type LiveNode } from './support/liveHost.js';

const IDENTITY = { host: 'fuaran-devtools-page-relay', hostVersion: '0.1.0' };

const page = (initial: LiveNode) => {
  const host = liveHost(initial);
  let deliver: ((envelope: RelayEnvelope) => void) | undefined;
  const peer = createPagePeer(host.surface, IDENTITY, {
    emit: (event) => queueMicrotask(() => deliver?.(event)),
  });
  const transport: RelayTransport = {
    post(envelope) {
      const response = peer.handle(envelope);
      if (response !== undefined) queueMicrotask(() => deliver?.(response));
    },
    listen(handler) {
      deliver = handler;
      return () => {
        deliver = undefined;
      };
    },
  };
  const client = new RelayClient(transport, { client: 'fuaran-devtools', clientVersion: '0.1.0' });
  return { host, client };
};

const tree = (): LiveNode =>
  node('root', 'Box', {}, [
    node('title', 'Heading', { level: 1, text: 'Quarterly review', variant: 'Standard' }),
    node('note', 'Callout', { body: 'Provisional.', tone: 'Info' }),
  ]);

/**
 * A panel-shaped session: read the tree, propose an op, record it only when the
 * host confirms. This is the `commit` path from `panel.ts`, minus the DOM.
 */
const session = (host: ReturnType<typeof page>) => {
  const trail = new Trail(() => '2020-01-01T00:00:00.000Z');
  trail.noteIdentity({ host: 'test', hostVersion: '0', profile: 'relay@1.0' });

  const readTree = async (): Promise<TreeSnapshot> => {
    const result = await host.client.readTree();
    if (!result.ok) throw new Error('read.tree failed');
    trail.observeTree(result.value, String(host.host.surface.treeRevision?.() ?? ''));
    return result.value;
  };

  const propose = async (op: TreeOpJson, reason: string): Promise<boolean> => {
    const result = await host.client.apply(op, { actor: 'fuaran-devtools', reason });
    if (!result.ok) return false;
    await trail.record(op, reason, result.value.treeRevision);
    await readTree();
    return true;
  };

  const undo = async (): Promise<boolean> => {
    const inverse = trail.undoOp();
    if (inverse === undefined || !inverse.ok) return false;
    const result = await host.client.apply(inverse.op, {
      actor: 'fuaran-devtools',
      reason: 'undo',
    });
    if (!result.ok) return false;
    trail.confirmUndo(result.value.treeRevision);
    await readTree();
    return true;
  };

  return { trail, readTree, propose, undo };
};

/**
 * Verify a document's chain the way an ingest does: walk it, recompute every
 * hash from the op bytes and the recorded actor, and check the links.
 *
 * It re-derives the ASSEMBLY independently — sequence, links, and each op's
 * canonical bytes recomputed from the parsed JSON rather than read from what
 * the writer stored — while sharing the pre-image primitive with the writer.
 * The primitive is pinned separately, against the golden corpus.
 */
const verifyChain = async (document: string): Promise<{ ok: boolean; reason?: string }> => {
  const parsed = JSON.parse(document) as {
    baseHash: string;
    ops: { seq: number; actor: Actor; prevHash: string; hash: string; op: unknown }[];
  };
  let previous = parsed.baseHash;
  for (const [index, entry] of parsed.ops.entries()) {
    if (entry.seq !== index + 1) return { ok: false, reason: `seq ${entry.seq} out of order` };
    if (entry.prevHash !== previous) return { ok: false, reason: `seq ${entry.seq} does not link` };
    const computed = await computeHash(
      previous,
      canonicalJson(entry.op as never),
      entry.seq,
      1_577_836_800,
      entry.actor,
      undefined,
      { kind: 'success' },
    );
    if (computed !== entry.hash) return { ok: false, reason: `seq ${entry.seq} hash mismatch` };
    previous = computed;
  }
  return { ok: true };
};

describe('undo restores the page', () => {
  it('leaves the host tree byte-identical after undoing a property edit', async () => {
    const host = page(tree());
    await host.client.hello();
    const panel = session(host);
    await panel.readTree();

    // The FIRST edit to a field has no recoverable prior value, so the session
    // sets it once to establish one — which is itself the honest behaviour
    // being exercised, not a workaround.
    expect(await panel.propose(updateProp('title', 'Text', 'first'), 'set Text')).toBe(true);
    const before = JSON.stringify(host.host.current());

    expect(await panel.propose(updateProp('title', 'Text', 'second'), 'set Text')).toBe(true);
    expect(JSON.stringify(host.host.current())).not.toBe(before);

    expect(await panel.undo()).toBe(true);
    expect(JSON.stringify(host.host.current())).toBe(before);
  });

  it('leaves the host tree byte-identical after undoing an insert-and-place', async () => {
    const host = page(tree());
    await host.client.hello();
    const panel = session(host);
    const snapshot = await panel.readTree();
    const before = JSON.stringify(host.host.current());

    const child = { id: 'heading-9', kind: { $type: 'Heading', level: 2, text: 'New' } };
    const op = insertOp(
      snapshot.children.map((entry) => entry.id),
      { parentId: 'root', placement: { at: 'before', anchor: 'note' } },
      child,
    );
    expect(await panel.propose(op, 'insert a Heading')).toBe(true);
    expect(host.host.current().children.map((entry) => entry.id)).toEqual([
      'title',
      'heading-9',
      'note',
    ]);

    expect(await panel.undo()).toBe(true);
    // Order and content both — the reorder leg is undone by the removal alone,
    // and this is the assertion that proves it rather than assumes it.
    expect(JSON.stringify(host.host.current())).toBe(before);
  });

  it('does not offer an undo it cannot honour', async () => {
    const host = page(tree());
    await host.client.hello();
    const panel = session(host);
    await panel.readTree();

    expect(await panel.propose(removeNode('note'), 'remove note')).toBe(true);
    expect(await panel.undo()).toBe(false);
    // The op stays in the trail: it happened, and the record is of what
    // happened, not of what can be reversed.
    expect(panel.trail.view().applied).toBe(1);
    expect(panel.trail.view().undoBlocked).toContain('cannot be restored');
  });
});

describe('refusals never enter the trail', () => {
  it('records nothing for a validator rejection, and the tree is unchanged', async () => {
    const host = page(tree());
    await host.client.hello();
    const panel = session(host);
    await panel.readTree();
    const before = JSON.stringify(host.host.current());

    expect(await panel.propose(removeNode('root'), 'remove the root')).toBe(false);
    expect(await panel.propose(updateProp('title', 'NotAField', 'x'), 'set NotAField')).toBe(false);
    expect(await panel.propose(updateProp('ghost', 'Text', 'x'), 'set Text')).toBe(false);

    expect(panel.trail.view().recorded).toBe(0);
    expect(JSON.stringify(host.host.current())).toBe(before);
    expect(JSON.parse(panel.trail.exportDocument())['ops']).toEqual([]);
  });

  it('records nothing for a policy denial', async () => {
    const host = page(tree());
    await host.client.hello();
    const panel = session(host);
    await panel.readTree();

    host.host.denyNext();
    expect(await panel.propose(updateProp('title', 'Text', 'x'), 'set Text')).toBe(false);
    expect(panel.trail.view().recorded).toBe(0);
  });

  it('keeps the chain contiguous across a refusal between two applied ops', async () => {
    const host = page(tree());
    await host.client.hello();
    const panel = session(host);
    await panel.readTree();

    expect(await panel.propose(updateProp('title', 'Text', 'one'), 'set Text')).toBe(true);
    host.host.denyNext();
    expect(await panel.propose(updateProp('title', 'Text', 'refused'), 'set Text')).toBe(false);
    expect(await panel.propose(updateProp('title', 'Text', 'two'), 'set Text')).toBe(true);

    const ops = JSON.parse(panel.trail.exportDocument())['ops'] as Record<string, unknown>[];
    expect(ops.map((op) => op['seq'])).toEqual([1, 2]);
    expect(await verifyChain(panel.trail.exportDocument())).toEqual({ ok: true });
  });
});

describe('the exported document verifies', () => {
  it('passes an independent chain recomputation over a real session', async () => {
    const host = page(tree());
    await host.client.hello();
    const panel = session(host);
    const snapshot = await panel.readTree();

    await panel.propose(updateProp('title', 'Text', 'Q3 review'), 'set Text');
    await panel.propose(updateProp('note', 'Body', 'Unaudited.'), 'set Body');
    await panel.propose(
      insertOp(
        snapshot.children.map((entry) => entry.id),
        { parentId: 'root', placement: { at: 'last' } },
        { id: 'badge-1', kind: { $type: 'Badge', label: 'draft', variant: 'Neutral' } },
      ),
      'insert a Badge',
    );

    const document = panel.trail.exportDocument();
    expect(await verifyChain(document)).toEqual({ ok: true });

    const parsed = JSON.parse(document) as Record<string, unknown>;
    expect((parsed['ops'] as unknown[]).length).toBe(3);
    expect(parsed['baseHash']).toBe(GENESIS_PREVIOUS_HASH);
    // Every op is attributed, and the attribution is inside the hash.
    for (const op of parsed['ops'] as Record<string, unknown>[])
      expect(op['actor']).toEqual({ kind: 'human', id: 'devtools' });
  });

  it('fails that recomputation when an op is re-attributed — attribution is evidence', async () => {
    const host = page(tree());
    await host.client.hello();
    const panel = session(host);
    await panel.readTree();
    await panel.propose(updateProp('title', 'Text', 'Q3 review'), 'set Text');

    const tampered = panel.trail
      .exportDocument()
      .replace(
        '{"kind":"human","id":"devtools"}',
        '{"kind":"agent","model":"m","version":"","id":"e"}',
      );
    const verdict = await verifyChain(tampered);
    expect(verdict.ok).toBe(false);
    expect(verdict.reason).toContain('hash mismatch');
  });

  it('excludes an undone op from the document', async () => {
    const host = page(tree());
    await host.client.hello();
    const panel = session(host);
    await panel.readTree();

    await panel.propose(updateProp('title', 'Text', 'one'), 'set Text');
    await panel.propose(updateProp('title', 'Text', 'two'), 'set Text');
    expect(await panel.undo()).toBe(true);

    const document = panel.trail.exportDocument();
    expect((JSON.parse(document)['ops'] as unknown[]).length).toBe(1);
    expect(document).not.toContain('"two"');
    expect(await verifyChain(document)).toEqual({ ok: true });
  });
});
